language: r
warnings_are_errors: true
sudo: true
dist: bionic

before_install:
#  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get update -qq
  - sudo apt-get install -y cppcheck
  - sudo apt-get install -qq lcov
  - sudo apt-get install -qq doxygen graphviz
  - sudo apt-get install -qq sqlite3 libsqlite3-dev
#  - sudo apt-get install -qq openjdk-7-jdk
  - sudo apt-get install -qq libproj13-dev


after_success:
  - Rscript -e 'covr::codecov()'

