language: r
warnings_are_errors: true
sudo: true

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt update
  - sudo apt upgrade
  - sudo apt install libproj-dev


after_success:
  - Rscript -e 'covr::codecov()'

