language: r
warnings_are_errors: true
sudo: true
dist: bionic  # 16.04

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get update
  - sudo apt-get upgrade -y
  - sudo apt-get install --assume-yes libproj-dev
  

after_success:
  - Rscript -e 'covr::codecov()'

